//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputBox.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InputBox.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Interrupt announcements disabled. All messages will be announced in full. 的當地語系化字串。
        /// </summary>
        internal static string A11y_A11yInterrupt_Off {
            get {
                return ResourceManager.GetString("A11y_A11yInterrupt_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interrupt announcements enabled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_A11yInterrupt_On {
            get {
                return ResourceManager.GetString("A11y_A11yInterrupt_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Animated visual alerts disabled. Warnings will use a single static pulse. 的當地語系化字串。
        /// </summary>
        internal static string A11y_AnimatedVisualAlerts_Off {
            get {
                return ResourceManager.GetString("A11y_AnimatedVisualAlerts_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Animated visual alerts enabled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_AnimatedVisualAlerts_On {
            get {
                return ResourceManager.GetString("A11y_AnimatedVisualAlerts_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Background task error: {0} 的當地語系化字串。
        /// </summary>
        internal static string A11y_Background_Error {
            get {
                return ResourceManager.GetString("A11y_Background_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel changes and close the dialog. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_Cancel_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_Cancel_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Decreases the numeric value. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_Minus_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_Minus_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm and apply the current value. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_OK_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_OK_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Increases the numeric value. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_Plus_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_Plus_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset the value to the factory default: {0}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_SetDefault_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_SetDefault_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset all settings in this group to their factory defaults. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Btn_SetDefault_Group_Desc {
            get {
                return ResourceManager.GetString("A11y_Btn_SetDefault_Group_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copies the text from the input box to the clipboard. 的當地語系化字串。
        /// </summary>
        internal static string A11y_BtnCopyDesc {
            get {
                return ResourceManager.GetString("A11y_BtnCopyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy to clipboard 的當地語系化字串。
        /// </summary>
        internal static string A11y_BtnCopyName {
            get {
                return ResourceManager.GetString("A11y_BtnCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action buttons area 的當地語系化字串。
        /// </summary>
        internal static string A11y_ButtonArea {
            get {
                return ResourceManager.GetString("A11y_ButtonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation cancelled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Cancelled {
            get {
                return ResourceManager.GetString("A11y_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot delete at the beginning. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Cannot_Delete {
            get {
                return ResourceManager.GetString("A11y_Cannot_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey capture cancelled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Capture_Cancelled {
            get {
                return ResourceManager.GetString("A11y_Capture_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Press ESC key to cancel. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Capture_Esc_Cancel {
            get {
                return ResourceManager.GetString("A11y_Capture_Esc_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checked 的當地語系化字串。
        /// </summary>
        internal static string A11y_Checked {
            get {
                return ResourceManager.GetString("A11y_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clipboard busy, retrying... 的當地語系化字串。
        /// </summary>
        internal static string A11y_Clipboard_Retrying {
            get {
                return ResourceManager.GetString("A11y_Clipboard_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contains privacy mode, hotkey settings, advanced settings, and other application functions. 的當地語系化字串。
        /// </summary>
        internal static string A11y_ContextMenu_Desc {
            get {
                return ResourceManager.GetString("A11y_ContextMenu_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feature Menu 的當地語系化字串。
        /// </summary>
        internal static string A11y_ContextMenu_Name {
            get {
                return ResourceManager.GetString("A11y_ContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current value: {0}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_CurrentValue {
            get {
                return ResourceManager.GetString("A11y_CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cursor at character {0} 的當地語系化字串。
        /// </summary>
        internal static string A11y_Cursor_Move {
            get {
                return ResourceManager.GetString("A11y_Cursor_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cursor moved. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Cursor_Move_PrivacySafe {
            get {
                return ResourceManager.GetString("A11y_Cursor_Move_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleted {0}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Delete_Char {
            get {
                return ResourceManager.GetString("A11y_Delete_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Character deleted. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Delete_Char_PrivacySafe {
            get {
                return ResourceManager.GetString("A11y_Delete_Char_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleted {0} characters. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Delete_Multiple {
            get {
                return ResourceManager.GetString("A11y_Delete_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controller {0} connected. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Gamepad_Connected {
            get {
                return ResourceManager.GetString("A11y_Gamepad_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controller {0} disconnected. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Gamepad_Disconnected {
            get {
                return ResourceManager.GetString("A11y_Gamepad_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GameInput initialization failed. Switched to XInput compatibility mode. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Gamepad_Fallback {
            get {
                return ResourceManager.GetString("A11y_Gamepad_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contains the numeric input field and increment/decrement buttons. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Grid_Numeric_Desc {
            get {
                return ResourceManager.GetString("A11y_Grid_Numeric_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 History {0} of {1}: {2} 的當地語系化字串。
        /// </summary>
        internal static string A11y_History_Navigation {
            get {
                return ResourceManager.GetString("A11y_History_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey set to {0}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Hotkey_Captured {
            get {
                return ResourceManager.GetString("A11y_Hotkey_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input Area 的當地語系化字串。
        /// </summary>
        internal static string A11y_Layout_Input {
            get {
                return ResourceManager.GetString("A11y_Layout_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Container housing the text input field. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Layout_Input_Desc {
            get {
                return ResourceManager.GetString("A11y_Layout_Input_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Main Layout 的當地語系化字串。
        /// </summary>
        internal static string A11y_Layout_Main {
            get {
                return ResourceManager.GetString("A11y_Layout_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Container holding the text input and action buttons. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Layout_Main_Desc {
            get {
                return ResourceManager.GetString("A11y_Layout_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Press A or Start to open keyboard when empty, or copy and return when text is entered. Use X to backspace, D-pad to move cursor or history. Press Back to return. LB + RB + B to quick return. LB + RB + X to exit. Keyboard: Enter to copy/open, Esc to clear, Up/Down for history, Alt + B to return. 的當地語系化字串。
        /// </summary>
        internal static string A11y_MainFormDesc {
            get {
                return ResourceManager.GetString("A11y_MainFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text input and copy 的當地語系化字串。
        /// </summary>
        internal static string A11y_MainFormName {
            get {
                return ResourceManager.GetString("A11y_MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quit the application and release all resources. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Exit_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Exit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configure vibration feedback and intensity levels. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Feedback_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Feedback_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configure controller deadzones, repeat speed, and API provider. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Gamepad_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Gamepad_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}. Current: {1}, Range: {2} to {3}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_NumericDesc {
            get {
                return ResourceManager.GetString("A11y_Menu_NumericDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}. Current: {1:P0}. Minimum is 10%. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_OpacityDesc {
            get {
                return ResourceManager.GetString("A11y_Menu_OpacityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select the underlying API for controller input (GameInput or XInput). 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Provider_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Provider_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Microsoft&apos;s modern GameInput API. Recommended for modern controllers. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Provider_GameInput_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Provider_GameInput_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use legacy XInput API. Best for compatibility with older devices. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Provider_XInput_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Provider_XInput_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open advanced settings including window behavior, feedback, and gamepad options. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Settings_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_Settings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Entering {0} submenu 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Submenu_Enter {
            get {
                return ResourceManager.GetString("A11y_Menu_Submenu_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exiting {0} submenu 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_Submenu_Exit {
            get {
                return ResourceManager.GetString("A11y_Menu_Submenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle all controller vibration effects on or off. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_VibEnable_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_VibEnable_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configure window restore delays and clipboard retry settings. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Menu_WinOps_Desc {
            get {
                return ResourceManager.GetString("A11y_Menu_WinOps_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize on return disabled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_MinimizeOnReturn_Off {
            get {
                return ResourceManager.GetString("A11y_MinimizeOnReturn_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize on return enabled. 的當地語系化字串。
        /// </summary>
        internal static string A11y_MinimizeOnReturn_On {
            get {
                return ResourceManager.GetString("A11y_MinimizeOnReturn_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Main key not set) 的當地語系化字串。
        /// </summary>
        internal static string A11y_Mod_Key_Missing {
            get {
                return ResourceManager.GetString("A11y_Mod_Key_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} disabled 的當地語系化字串。
        /// </summary>
        internal static string A11y_Mod_Off {
            get {
                return ResourceManager.GetString("A11y_Mod_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} enabled 的當地語系化字串。
        /// </summary>
        internal static string A11y_Mod_On {
            get {
                return ResourceManager.GetString("A11y_Mod_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle {0} as a modifier for the wake up hotkey. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Mod_Toggle_Desc {
            get {
                return ResourceManager.GetString("A11y_Mod_Toggle_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End of text reached. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Nav_Bottom {
            get {
                return ResourceManager.GetString("A11y_Nav_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Returned to latest input. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Nav_Newest {
            get {
                return ResourceManager.GetString("A11y_Nav_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No older history items. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Nav_Oldest {
            get {
                return ResourceManager.GetString("A11y_Nav_Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start of text reached. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Nav_Top {
            get {
                return ResourceManager.GetString("A11y_Nav_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New line added. 的當地語系化字串。
        /// </summary>
        internal static string A11y_New_Line {
            get {
                return ResourceManager.GetString("A11y_New_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No text to copy. 的當地語系化字串。
        /// </summary>
        internal static string A11y_No_Text_To_Copy {
            get {
                return ResourceManager.GetString("A11y_No_Text_To_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity set to {0:P0}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Opacity_Changed {
            get {
                return ResourceManager.GetString("A11y_Opacity_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 High Contrast mode is on, opacity locked to 100%. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Opacity_HighContrast {
            get {
                return ResourceManager.GetString("A11y_Opacity_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opening touch keyboard. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Opening_Keyboard {
            get {
                return ResourceManager.GetString("A11y_Opening_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy mode disabled 的當地語系化字串。
        /// </summary>
        internal static string A11y_PrivacyMode_Off {
            get {
                return ResourceManager.GetString("A11y_PrivacyMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy mode enabled 的當地語系化字串。
        /// </summary>
        internal static string A11y_PrivacyMode_On {
            get {
                return ResourceManager.GetString("A11y_PrivacyMode_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Returning to previous window. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Returning {
            get {
                return ResourceManager.GetString("A11y_Returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selected: {0} 的當地語系化字串。
        /// </summary>
        internal static string A11y_Selected_Text {
            get {
                return ResourceManager.GetString("A11y_Selected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text selected. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Selected_Text_PrivacySafe {
            get {
                return ResourceManager.GetString("A11y_Selected_Text_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  (Restart required) 的當地語系化字串。
        /// </summary>
        internal static string A11y_Settings_RestartRequired {
            get {
                return ResourceManager.GetString("A11y_Settings_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Focus moved to text input 的當地語系化字串。
        /// </summary>
        internal static string A11y_SkipNav_JumpToInput {
            get {
                return ResourceManager.GetString("A11y_SkipNav_JumpToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window position corrected automatically. 的當地語系化字串。
        /// </summary>
        internal static string A11y_SnapBack {
            get {
                return ResourceManager.GetString("A11y_SnapBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Wake up hotkey: {1}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Startup_Status {
            get {
                return ResourceManager.GetString("A11y_Startup_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Focused 的當地語系化字串。
        /// </summary>
        internal static string A11y_State_Focused {
            get {
                return ResourceManager.GetString("A11y_State_Focused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hovering 的當地語系化字串。
        /// </summary>
        internal static string A11y_State_Hover {
            get {
                return ResourceManager.GetString("A11y_State_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pressed 的當地語系化字串。
        /// </summary>
        internal static string A11y_State_Pressed {
            get {
                return ResourceManager.GetString("A11y_State_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot return: The target window has been closed. 的當地語系化字串。
        /// </summary>
        internal static string A11y_TargetWindowLost {
            get {
                return ResourceManager.GetString("A11y_TargetWindowLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the text you want to copy to the clipboard here. 的當地語系化字串。
        /// </summary>
        internal static string A11y_TBInputDesc {
            get {
                return ResourceManager.GetString("A11y_TBInputDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter Text 的當地語系化字串。
        /// </summary>
        internal static string A11y_TBInputName {
            get {
                return ResourceManager.GetString("A11y_TBInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System theme has changed. Please select &quot;Apply System Theme&quot; from the context menu to restart the application and fully apply visual effects. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Theme_Changed_Hint {
            get {
                return ResourceManager.GetString("A11y_Theme_Changed_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unchecked 的當地語系化字串。
        /// </summary>
        internal static string A11y_Unchecked {
            get {
                return ResourceManager.GetString("A11y_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maximum value reached. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Value_Max {
            get {
                return ResourceManager.GetString("A11y_Value_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimum value reached. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Value_Min {
            get {
                return ResourceManager.GetString("A11y_Value_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current value: {0}. Valid range: {1} to {2}. 的當地語系化字串。
        /// </summary>
        internal static string A11y_Value_Range_Desc {
            get {
                return ResourceManager.GetString("A11y_Value_Range_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GameInput: {0} 的當地語系化字串。
        /// </summary>
        internal static string App_Gamepad_Suffix {
            get {
                return ResourceManager.GetString("App_Gamepad_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 XInput: {0} 的當地語系化字串。
        /// </summary>
        internal static string App_Gamepad_XInput_Format {
            get {
                return ResourceManager.GetString("App_Gamepad_XInput_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  (🔒) 的當地語系化字串。
        /// </summary>
        internal static string App_Privacy_Suffix {
            get {
                return ResourceManager.GetString("App_Privacy_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 🔄 的當地語系化字串。
        /// </summary>
        internal static string App_ThemePending_Suffix {
            get {
                return ResourceManager.GetString("App_ThemePending_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 InputBox 的當地語系化字串。
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abort 的當地語系化字串。
        /// </summary>
        internal static string Btn_Abort {
            get {
                return ResourceManager.GetString("Btn_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy to clipboard 的當地語系化字串。
        /// </summary>
        internal static string Btn_CopyDefault {
            get {
                return ResourceManager.GetString("Btn_CopyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ignore 的當地語系化字串。
        /// </summary>
        internal static string Btn_Ignore {
            get {
                return ResourceManager.GetString("Btn_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 － 的當地語系化字串。
        /// </summary>
        internal static string Btn_Minus {
            get {
                return ResourceManager.GetString("Btn_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        internal static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＋ 的當地語系化字串。
        /// </summary>
        internal static string Btn_Plus {
            get {
                return ResourceManager.GetString("Btn_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Retry 的當地語系化字串。
        /// </summary>
        internal static string Btn_Retry {
            get {
                return ResourceManager.GetString("Btn_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset to Default 的當地語系化字串。
        /// </summary>
        internal static string Btn_SetDefault {
            get {
                return ResourceManager.GetString("Btn_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        internal static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The configuration file format is invalid. The application will start with default settings. 的當地語系化字串。
        /// </summary>
        internal static string Err_ConfigInvalid {
            get {
                return ResourceManager.GetString("Err_ConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gamepad controller initialization failed. Some features may be unavailable. 的當地語系化字串。
        /// </summary>
        internal static string Err_GamepadInitFail {
            get {
                return ResourceManager.GetString("Err_GamepadInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Global hotkey {0} failed to register.
        ///
        ///Make sure that multiple instances of this application are not running at the same time, or that another application is not already using this hotkey. 的當地語系化字串。
        /// </summary>
        internal static string Err_HotkeyRegFail {
            get {
                return ResourceManager.GetString("Err_HotkeyRegFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey registration failed. Reverted to previous setting. 的當地語系化字串。
        /// </summary>
        internal static string Err_HotkeyRegFail_Brief {
            get {
                return ResourceManager.GetString("Err_HotkeyRegFail_Brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string Err_Title {
            get {
                return ResourceManager.GetString("Err_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Touch keyboard not found. 的當地語系化字串。
        /// </summary>
        internal static string Err_TouchKeyboardNotFound {
            get {
                return ResourceManager.GetString("Err_TouchKeyboardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message dialog. Press A for the primary action, B to cancel. 的當地語系化字串。
        /// </summary>
        internal static string GmBox_A11y_Dialog_Desc {
            get {
                return ResourceManager.GetString("GmBox_A11y_Dialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A: {0} · B: {1} 的當地語系化字串。
        /// </summary>
        internal static string GmBox_A11y_Hint {
            get {
                return ResourceManager.GetString("GmBox_A11y_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shows keyboard shortcuts and gamepad controls. Use arrow keys, Page Up, Page Down, or the gamepad to scroll, then choose Close to return. 的當地語系化字串。
        /// </summary>
        internal static string Help_A11y_Dialog_Desc {
            get {
                return ResourceManager.GetString("Help_A11y_Dialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gamepad controls table 的當地語系化字串。
        /// </summary>
        internal static string Help_A11y_Gamepad_Group {
            get {
                return ResourceManager.GetString("Help_A11y_Gamepad_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lists the available gamepad buttons and their actions. 的當地語系化字串。
        /// </summary>
        internal static string Help_A11y_Gamepad_Group_Desc {
            get {
                return ResourceManager.GetString("Help_A11y_Gamepad_Group_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keyboard shortcuts table 的當地語系化字串。
        /// </summary>
        internal static string Help_A11y_Keyboard_Group {
            get {
                return ResourceManager.GetString("Help_A11y_Keyboard_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lists the available keyboard shortcuts and their actions. 的當地語系化字串。
        /// </summary>
        internal static string Help_A11y_Keyboard_Group_Desc {
            get {
                return ResourceManager.GetString("Help_A11y_Keyboard_Group_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Help_Btn_Close {
            get {
                return ResourceManager.GetString("Help_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        internal static string Help_Col_Action {
            get {
                return ResourceManager.GetString("Help_Col_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Button 的當地語系化字串。
        /// </summary>
        internal static string Help_Col_Button {
            get {
                return ResourceManager.GetString("Help_Col_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Key 的當地語系化字串。
        /// </summary>
        internal static string Help_Col_Key {
            get {
                return ResourceManager.GetString("Help_Col_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A / Start	Confirm &amp; Return (or open OSK)
        ///B	Clear input text
        ///LB + RB + B	Quick return to previous window
        ///Back (release)	Return to previous window
        ///Y	Open feature menu
        ///X	Backspace (Delete character/selection)
        ///LB + RB + X	Exit application
        ///Back + X	Reset window opacity
        ///↑ / ↓	Navigate history
        ///← / →	Move cursor left / right
        ///LB + ← / →	Jump cursor by word
        ///RS ← / →	Expand or shrink selection
        ///Back + ↑ / ↓	Adjust window opacity (±5%) 的當地語系化字串。
        /// </summary>
        internal static string Help_Gamepad_Rows {
            get {
                return ResourceManager.GetString("Help_Gamepad_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Esc	Clear input / Return to previous window (if empty)
        ///Enter	Copy to clipboard and return (or open OSK)
        ///Alt + A	Same as Enter
        ///Shift + Enter	Insert a new line
        ///F1	Open this Help dialog
        ///↑ / ↓	Navigate history
        ///← / →	Move cursor left / right
        ///Shift + ← / →	Select text
        ///Home / End	Jump cursor to line start / end
        ///Ctrl + ← / →	Move cursor by word
        ///Backspace	Delete previous character or selection
        ///Delete	Delete next character
        ///Alt + B	Return to previous window without copying
        ///Alt + ↑ / ↓	Increase / decrease  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Help_Keyboard_Rows {
            get {
                return ResourceManager.GetString("Help_Keyboard_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gamepad Controls 的當地語系化字串。
        /// </summary>
        internal static string Help_Section_Gamepad {
            get {
                return ResourceManager.GetString("Help_Section_Gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keyboard Shortcuts 的當地語系化字串。
        /// </summary>
        internal static string Help_Section_Keyboard {
            get {
                return ResourceManager.GetString("Help_Section_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Help — Keyboard Shortcuts &amp; Gamepad Controls 的當地語系化字串。
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interrupt Announcements 的當地語系化字串。
        /// </summary>
        internal static string Menu_A11yInterrupt {
            get {
                return ResourceManager.GetString("Menu_A11yInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow announcements to interrupt the previous one. Disable to hear every message in full. 的當地語系化字串。
        /// </summary>
        internal static string Menu_A11yInterrupt_Desc {
            get {
                return ResourceManager.GetString("Menu_A11yInterrupt_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Animated Visual Alerts 的當地語系化字串。
        /// </summary>
        internal static string Menu_AnimatedVisualAlerts {
            get {
                return ResourceManager.GetString("Menu_AnimatedVisualAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow 1 hertz animated visual alerts. Disable to use a single static pulse, which is safer for light-sensitive users. 的當地語系化字串。
        /// </summary>
        internal static string Menu_AnimatedVisualAlerts_Desc {
            get {
                return ResourceManager.GetString("Menu_AnimatedVisualAlerts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply System Theme (Restart Required) 的當地語系化字串。
        /// </summary>
        internal static string Menu_ApplyThemeRestart {
            get {
                return ResourceManager.GetString("Menu_ApplyThemeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Capture Key... 的當地語系化字串。
        /// </summary>
        internal static string Menu_CaptureKey {
            get {
                return ResourceManager.GetString("Menu_CaptureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start capturing a new key from the keyboard. 的當地語系化字串。
        /// </summary>
        internal static string Menu_CaptureKey_Desc {
            get {
                return ResourceManager.GetString("Menu_CaptureKey_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear History 的當地語系化字串。
        /// </summary>
        internal static string Menu_ClearHistory {
            get {
                return ResourceManager.GetString("Menu_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permanently clear all input records currently in memory. 的當地語系化字串。
        /// </summary>
        internal static string Menu_ClearHistory_Desc {
            get {
                return ResourceManager.GetString("Menu_ClearHistory_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Help 的當地語系化字串。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show keyboard shortcuts and gamepad controls (F1) 的當地語系化字串。
        /// </summary>
        internal static string Menu_Help_Desc {
            get {
                return ResourceManager.GetString("Menu_Help_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey Settings 的當地語系化字串。
        /// </summary>
        internal static string Menu_HotkeySettings {
            get {
                return ResourceManager.GetString("Menu_HotkeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configure the global hotkeys to wake up the input box. 的當地語系化字串。
        /// </summary>
        internal static string Menu_HotkeySettings_Desc {
            get {
                return ResourceManager.GetString("Menu_HotkeySettings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage Phrases… 的當地語系化字串。
        /// </summary>
        internal static string Menu_ManagePhrases {
            get {
                return ResourceManager.GetString("Menu_ManagePhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize on Return 的當地語系化字串。
        /// </summary>
        internal static string Menu_MinimizeOnReturn {
            get {
                return ResourceManager.GetString("Menu_MinimizeOnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize InputBox when returning to the previous window. 的當地語系化字串。
        /// </summary>
        internal static string Menu_MinimizeOnReturn_Desc {
            get {
                return ResourceManager.GetString("Menu_MinimizeOnReturn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Folder 的當地語系化字串。
        /// </summary>
        internal static string Menu_OpenDataFolder {
            get {
                return ResourceManager.GetString("Menu_OpenDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open the application data folder in AppData. 的當地語系化字串。
        /// </summary>
        internal static string Menu_OpenDataFolder_Desc {
            get {
                return ResourceManager.GetString("Menu_OpenDataFolder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Log Folder 的當地語系化字串。
        /// </summary>
        internal static string Menu_OpenLogFolder {
            get {
                return ResourceManager.GetString("Menu_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open the log file folder in AppData Local. 的當地語系化字串。
        /// </summary>
        internal static string Menu_OpenLogFolder_Desc {
            get {
                return ResourceManager.GetString("Menu_OpenLogFolder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (No phrases) 的當地語系化字串。
        /// </summary>
        internal static string Menu_PhraseEmpty {
            get {
                return ResourceManager.GetString("Menu_PhraseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrases 的當地語系化字串。
        /// </summary>
        internal static string Menu_Phrases {
            get {
                return ResourceManager.GetString("Menu_Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy Mode 的當地語系化字串。
        /// </summary>
        internal static string Menu_PrivacyMode {
            get {
                return ResourceManager.GetString("Menu_PrivacyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When enabled, new inputs will not be saved to history. 的當地語系化字串。
        /// </summary>
        internal static string Menu_PrivacyMode_Desc {
            get {
                return ResourceManager.GetString("Menu_PrivacyMode_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feedback 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Feedback {
            get {
                return ResourceManager.GetString("Menu_Settings_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gamepad 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Gamepad {
            get {
                return ResourceManager.GetString("Menu_Settings_Gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 History Capacity: {0} 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_HistoryCapacity {
            get {
                return ResourceManager.GetString("Menu_Settings_HistoryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Intensity: {0} 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Intensity {
            get {
                return ResourceManager.GetString("Menu_Settings_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gamepad Input API 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Provider {
            get {
                return ResourceManager.GetString("Menu_Settings_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vibration 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Vibration {
            get {
                return ResourceManager.GetString("Menu_Settings_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window &amp; Operations 的當地語系化字串。
        /// </summary>
        internal static string Menu_Settings_Window {
            get {
                return ResourceManager.GetString("Menu_Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alt 的當地語系化字串。
        /// </summary>
        internal static string Mod_Alt {
            get {
                return ResourceManager.GetString("Mod_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ctrl 的當地語系化字串。
        /// </summary>
        internal static string Mod_Ctrl {
            get {
                return ResourceManager.GetString("Mod_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shift 的當地語系化字串。
        /// </summary>
        internal static string Mod_Shift {
            get {
                return ResourceManager.GetString("Mod_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Win 的當地語系化字串。
        /// </summary>
        internal static string Mod_Win {
            get {
                return ResourceManager.GetString("Mod_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete the phrase &quot;{0}&quot;? This action cannot be undone. 的當地語系化字串。
        /// </summary>
        internal static string Msg_ConfirmDeletePhrase {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeletePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copied 的當地語系化字串。
        /// </summary>
        internal static string Msg_Copied {
            get {
                return ResourceManager.GetString("Msg_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy failed 的當地語系化字串。
        /// </summary>
        internal static string Msg_CopyFail {
            get {
                return ResourceManager.GetString("Msg_CopyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a new value for {0}: 的當地語系化字串。
        /// </summary>
        internal static string Msg_EnterValue {
            get {
                return ResourceManager.GetString("Msg_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The folder does not exist yet. 的當地語系化字串。
        /// </summary>
        internal static string Msg_FolderNotFound {
            get {
                return ResourceManager.GetString("Msg_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hotkey Updated 的當地語系化字串。
        /// </summary>
        internal static string Msg_HotkeyUpdated {
            get {
                return ResourceManager.GetString("Msg_HotkeyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input cleared 的當地語系化字串。
        /// </summary>
        internal static string Msg_InputCleared {
            get {
                return ResourceManager.GetString("Msg_InputCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting opacity below 50% may reduce readability when the background is complex. In High Contrast mode, InputBox always overrides this to 100%.
        ///
        ///Continue? 的當地語系化字串。
        /// </summary>
        internal static string Msg_LowOpacity_Warn {
            get {
                return ResourceManager.GetString("Msg_LowOpacity_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low Opacity Warning 的當地語系化字串。
        /// </summary>
        internal static string Msg_LowOpacity_Warn_Title {
            get {
                return ResourceManager.GetString("Msg_LowOpacity_Warn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 InputBox will minimize itself when you return to the previous window. Do you want to enable this feature? 的當地語系化字串。
        /// </summary>
        internal static string Msg_MinimizeOnReturn_Confirm {
            get {
                return ResourceManager.GetString("Msg_MinimizeOnReturn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize on Return 的當地語系化字串。
        /// </summary>
        internal static string Msg_MinimizeOnReturn_Confirm_Title {
            get {
                return ResourceManager.GetString("Msg_MinimizeOnReturn_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Press any key... 的當地語系化字串。
        /// </summary>
        internal static string Msg_PressAnyKey {
            get {
                return ResourceManager.GetString("Msg_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This change requires a restart to take effect. Restart now? 的當地語系化字串。
        /// </summary>
        internal static string Msg_RestartRequired {
            get {
                return ResourceManager.GetString("Msg_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase added: {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Added {
            get {
                return ResourceManager.GetString("Phrase_A11y_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase added. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Added_PrivacySafe {
            get {
                return ResourceManager.GetString("Phrase_A11y_Added_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add a new phrase. Gamepad: Y button. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Add_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Add_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel editing. Gamepad: B button. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Cancel_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Cancel_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close the phrase manager. Gamepad: B button. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Close_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Close_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm and save the phrase. Gamepad: A button. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Confirm_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Confirm_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the selected phrase. Gamepad: X button. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Delete_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Delete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit the selected phrase. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_Edit_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_Edit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move the selected phrase down. Gamepad: Right D-pad. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_MoveDown_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_MoveDown_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move the selected phrase up. Gamepad: Left D-pad. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Btn_MoveUp_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Btn_MoveUp_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase Actions 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_ButtonArea {
            get {
                return ResourceManager.GetString("Phrase_A11y_ButtonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contains action buttons for phrase operations. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_ButtonArea_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_ButtonArea_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter phrase content. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_ContentRequired {
            get {
                return ResourceManager.GetString("Phrase_A11y_ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase deleted: {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Deleted {
            get {
                return ResourceManager.GetString("Phrase_A11y_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase deleted. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Deleted_PrivacySafe {
            get {
                return ResourceManager.GetString("Phrase_A11y_Deleted_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage phrases: add, edit, delete, and reorder. Use gamepad Y to add, A to insert, X to delete, Left/Right to reorder. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Dialog_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Dialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the text content to be inserted (max 500 characters). Supports multiple lines. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Edit_Content_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Edit_Content_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter a name and content for the phrase. Press Enter or gamepad A to confirm. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Edit_Dialog_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Edit_Dialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter a display name for this phrase (max 50 characters). 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Edit_Name_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_Edit_Name_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase list is full. Cannot add more phrases. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Full {
            get {
                return ResourceManager.GetString("Phrase_A11y_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase inserted: {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Inserted {
            get {
                return ResourceManager.GetString("Phrase_A11y_Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase inserted. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Inserted_PrivacySafe {
            get {
                return ResourceManager.GetString("Phrase_A11y_Inserted_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a phrase and press Enter or gamepad A to insert it into the input box. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_List_Desc {
            get {
                return ResourceManager.GetString("Phrase_A11y_List_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase List 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_List_Name {
            get {
                return ResourceManager.GetString("Phrase_A11y_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Moved to position {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Moved {
            get {
                return ResourceManager.GetString("Phrase_A11y_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a phrase name. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_NameRequired {
            get {
                return ResourceManager.GetString("Phrase_A11y_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Page {0} of {1} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Page_Info {
            get {
                return ResourceManager.GetString("Phrase_A11y_Page_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next page 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Page_Next {
            get {
                return ResourceManager.GetString("Phrase_A11y_Page_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Previous page 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Page_Previous {
            get {
                return ResourceManager.GetString("Phrase_A11y_Page_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selected: {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Selected {
            get {
                return ResourceManager.GetString("Phrase_A11y_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase selected. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Selected_PrivacySafe {
            get {
                return ResourceManager.GetString("Phrase_A11y_Selected_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase updated: {0} 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Updated {
            get {
                return ResourceManager.GetString("Phrase_A11y_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase updated. 的當地語系化字串。
        /// </summary>
        internal static string Phrase_A11y_Updated_PrivacySafe {
            get {
                return ResourceManager.GetString("Phrase_A11y_Updated_PrivacySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Add {
            get {
                return ResourceManager.GetString("Phrase_Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Cancel {
            get {
                return ResourceManager.GetString("Phrase_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Close {
            get {
                return ResourceManager.GetString("Phrase_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Confirm {
            get {
                return ResourceManager.GetString("Phrase_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Delete {
            get {
                return ResourceManager.GetString("Phrase_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_Edit {
            get {
                return ResourceManager.GetString("Phrase_Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Down 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_MoveDown {
            get {
                return ResourceManager.GetString("Phrase_Btn_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Up 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Btn_MoveUp {
            get {
                return ResourceManager.GetString("Phrase_Btn_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Content: 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Content {
            get {
                return ResourceManager.GetString("Phrase_Edit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter phrase content... 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Content_Placeholder {
            get {
                return ResourceManager.GetString("Phrase_Edit_Content_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name: 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Name {
            get {
                return ResourceManager.GetString("Phrase_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter phrase name... 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Name_Placeholder {
            get {
                return ResourceManager.GetString("Phrase_Edit_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Phrase 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Title_Add {
            get {
                return ResourceManager.GetString("Phrase_Edit_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Phrase 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Edit_Title_Edit {
            get {
                return ResourceManager.GetString("Phrase_Edit_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phrase Manager 的當地語系化字串。
        /// </summary>
        internal static string Phrase_Title {
            get {
                return ResourceManager.GetString("Phrase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter text… 的當地語系化字串。
        /// </summary>
        internal static string Pht_TBInput {
            get {
                return ResourceManager.GetString("Pht_TBInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clipboard Retry Delay 的當地語系化字串。
        /// </summary>
        internal static string Settings_ClipboardRetryDelay {
            get {
                return ResourceManager.GetString("Settings_ClipboardRetryDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 History Capacity 的當地語系化字串。
        /// </summary>
        internal static string Settings_HistoryCapacity {
            get {
                return ResourceManager.GetString("Settings_HistoryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat Delay 的當地語系化字串。
        /// </summary>
        internal static string Settings_RepeatDelay {
            get {
                return ResourceManager.GetString("Settings_RepeatDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat Speed 的當地語系化字串。
        /// </summary>
        internal static string Settings_RepeatSpeed {
            get {
                return ResourceManager.GetString("Settings_RepeatSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Thumb Deadzone: Trigger Threshold 的當地語系化字串。
        /// </summary>
        internal static string Settings_ThumbDeadzoneEnter {
            get {
                return ResourceManager.GetString("Settings_ThumbDeadzoneEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Thumb Deadzone: Reset Threshold 的當地語系化字串。
        /// </summary>
        internal static string Settings_ThumbDeadzoneExit {
            get {
                return ResourceManager.GetString("Settings_ThumbDeadzoneExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Touch Keyboard Dismiss Delay 的當地語系化字串。
        /// </summary>
        internal static string Settings_TouchKeyboardDismissDelay {
            get {
                return ResourceManager.GetString("Settings_TouchKeyboardDismissDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Intensity 的當地語系化字串。
        /// </summary>
        internal static string Settings_VibrationIntensity {
            get {
                return ResourceManager.GetString("Settings_VibrationIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity 的當地語系化字串。
        /// </summary>
        internal static string Settings_WindowOpacity {
            get {
                return ResourceManager.GetString("Settings_WindowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window Restore Delay 的當地語系化字串。
        /// </summary>
        internal static string Settings_WindowRestoreDelay {
            get {
                return ResourceManager.GetString("Settings_WindowRestoreDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window Switch Buffer Base 的當地語系化字串。
        /// </summary>
        internal static string Settings_WindowSwitchBufferBase {
            get {
                return ResourceManager.GetString("Settings_WindowSwitchBufferBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        internal static string Wrn_Title {
            get {
                return ResourceManager.GetString("Wrn_Title", resourceCulture);
            }
        }
    }
}
